# Generated by Django 3.2.9 on 2021-11-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=60)),
                ('kategoriaPrawajazdy', models.CharField(max_length=20)),
                ('numerTelefonu', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('idSamochodu', models.AutoField(primary_key=True, serialize=False)),
                ('numerRejestracyjny', models.CharField(max_length=10)),
                ('marka', models.CharField(max_length=45)),
                ('typ', models.CharField(max_length=45)),
                ('kolor', models.CharField(max_length=45, null=True)),
                ('liczbaMiejsc', models.IntegerField()),
                ('liczbaDrzwi', models.IntegerField()),
                ('typPaliwa', models.CharField(max_length=45)),
                ('typSkrzyniBiegow', models.CharField(max_length=45)),
                ('uszkodzenia', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('idWypozyczenia', models.AutoField(primary_key=True, serialize=False)),
                ('dataStartu', models.DateTimeField()),
                ('dataKonca', models.DateTimeField()),
                ('MiejsceOdbioruSamochodu', models.CharField(max_length=100)),
                ('MiejsceZwrotuSamochodu', models.CharField(max_length=100)),
                ('canaWypozyczenia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
