# Generated by Django 3.2.9 on 2021-11-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wypozyczenie',
            name='klient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klienci', to='wypozyczalnia.klient'),
        ),
        migrations.AddField(
            model_name='wypozyczenie',
            name='samochod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samochody', to='wypozyczalnia.samochod'),
        ),
    ]
