# Generated by Django 3.2.9 on 2021-12-16 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wypozyczalnia', '0002_auto_20211125_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ('nazwisko',)},
        ),
        migrations.AlterModelOptions(
            name='samochod',
            options={'ordering': ('marka',)},
        ),
        migrations.AlterModelOptions(
            name='wypozyczenie',
            options={'ordering': ('MiejsceOdbioruSamochodu',)},
        ),
        migrations.AddField(
            model_name='samochod',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='samochody', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wypozyczenie',
            name='klient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wypozyczenia', to='wypozyczalnia.klient'),
        ),
        migrations.AlterField(
            model_name='wypozyczenie',
            name='samochod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wypozyczenia', to='wypozyczalnia.samochod'),
        ),
    ]
