# Generated by Django 3.2.9 on 2021-11-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_auto_20211125_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='klient',
            name='pesel',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
