# Generated by Django 3.2.9 on 2021-12-16 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wypozyczalnia', '0003_auto_20211216_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='klienci', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wypozyczenie',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wypozyczenia', to='auth.user'),
            preserve_default=False,
        ),
    ]
