# Generated by Django 3.2.9 on 2021-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0003_auto_20211125_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='id',
        ),
        migrations.AlterField(
            model_name='klient',
            name='pesel',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
